name: release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: "file-reader"
  # TARGET: "x86_64-pc-windows-msvc"
  CERT_FILE: "file-reader.pfx"

jobs:
  build-release:
    name: Build Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}
          path: target/release/${{ env.BINARY_NAME }}.exe

  create-release:
    needs: build-release
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}

      # - name: Create self-signed certificate
      #   shell: powershell
      #   run: |
      #     $cert = New-SelfSignedCertificate -Type CodeSigningCert -Subject "${{ env.CERT_NAME }}" -CertStoreLocation "Cert:\CurrentUser\My"
      #     $pwd = ConvertTo-SecureString -String "${{ env.CERT_PASSWORD }}" -Force -AsPlainText
      #     Export-PfxCertificate -Cert $cert -FilePath "${{ env.CERT_FILE }}" -Password $pwd

      # - name: Sign EXE using signtool
      #   run: |
      #     "Signing ${{ env.BINARY_NAME }}.exe"
      #     signtool sign /fd SHA256 /f ${{ env.CERT_FILE }} /p ${{ env.CERT_PASSWORD }} ${{ env.BINARY_NAME }}.exe

      - name: Decode PFX certificate
        shell: powershell
        run: |
          [IO.File]::WriteAllBytes("${{ env.CERT_FILE }}", [Convert]::FromBase64String("${{ secrets.PFX_CERT_BASE64 }}"))

      - name: Sign EXE
        run: |
          $kitPath = "${env:ProgramFiles(x86)}\Windows Kits\10\bin"
          $signtool = Get-ChildItem -Path $kitPath -Recurse -Filter signtool.exe |
                Where-Object { $_.FullName -like "*x64*" } |
                Sort-Object FullName -Descending |
                Select-Object -First 1
          & $signtool.FullName sign /fd SHA256 /f ${{ env.CERT_FILE }} /p "${{ secrets.PFX_PASSWORD }}" ${{ env.BINARY_NAME }}.exe

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.BINARY_NAME }}.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
